version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./SmartHotels.Services.All.sln && dotnet publish ./SmartHotels.Services.All.sln -c Release -o ./obj/Docker/publish"
